### ISSUE TITLE
Remote File - "Path not found"

### ISSUE THREAD

**Issue by franalt** [DataGarage/node-xls-json#20]
Hey everyone. I'm trying to use a file located in a URL.

I've tried the following with no success. I get "Path not found".

node_xj({
    input: "http://www.page.com/File.xls",  // input xls 
    output: "output.json", // output json 
    sheet: "Hoja1"  // specific sheetname 
  }, function(err, result) {
    if(err) {
      console.error(err);
    } else {
      console.log(result);
    }
});

Thanks

**Comment by rodrigograca31** [comment]
This package doesn't support URLs....

Can't you just download the file....?
