### ISSUE TITLE
Update xlsx version

### ISSUE THREAD

**Issue by carloshpds** [DataGarage/node-xls-json#23]
The version `0.8.x` is not compatible with webpack, there is an errant `require('./cptable')` which does not exist. [Reported in #554](https://github.com/SheetJS/js-xlsx/issues/554)

**Comment by carloshpds** [comment]
An alternative for people which has this problem until `node-xls-json` update the version of `xlsx`:

webpack.config.js
```javascript
     externals: {
        './cptable': 'var cptable',
        '../xlsx.js': 'var _XLSX'
      }
```

This is an alternative commented by xlxs owner [here](https://github.com/SheetJS/js-xlsx/issues/585#issuecomment-284941354) and works for me.

**Comment by rodrigograca31** [comment]
I guess this isn't an issue anymore?
