### ISSUE TITLE
getting blank result

### ISSUE THREAD

**Issue by anjali2908** [DataGarage/node-xls-json#24]
I have been trying to convert excel sheet data to json format and I have already various modules like "xls-to-json","xls-to-json-lc","node-excel-to-json", So far I have got empty response.

My sample code goes like this :

    var   node_xj = require("xls-to-json-lc");
  node_xj({
    input: req.file.path,  // input xls
    output: "output.json", // output json
    sheet: "a"  // specific sheetname
  }, function(err, result) {
    if(err) {
      console.error(err);
    } else {
      console.log("--------result----");
      console.log(result);
    }
  });
My excel sheet contains very simple data :

![a](https://user-images.githubusercontent.com/33183314/33241013-f901b29c-d2e5-11e7-815c-ad34c511b953.PNG)

**Comment by rodrigograca31** [comment]
I guess this isn't an issue anymore?
