### ISSUE TITLE
ENOENT: no such file or directory, open 'inputfile.xls'

### ISSUE THREAD

**Issue by leonardlepadatu** [DataGarage/node-xls-json#29]
ENV:
node v8.11.1
npm v5.6.0
"xls-to-json": "^0.5.0",

Code:
`
const node_xj = require('xls-to-json');
const usersJson = async () => new Promise((resolve, reject) => {
            node_xj({
                input: './inputfile.xls',
            }, (err, result) => {
                if (err) {
                    return reject(err);
                }
                return resolve(result);
            });
        });
`

Return:
`ERROR: ENOENT: no such file or directory, open './inputfile.xls'`

Thank you,
Leo

EDIT: 
`
[...]
   input: path.resolve('somedir/inputfile.js')
[...]
`
it seems that now find the path after resolve

**Comment by leonardlepadatu** [comment]
After digging a little bit, I realize that config.output must be specified with NULL value:
`node_xj({
                input: inputFilePath,
                output: null
 },`

Otherwise fs will throw:
`TypeError: path must be a string or Buffer`
`at CSV.<anonymous> (/.../xls-to-json/libs/index.js:65:24)`

Thank you

**Comment by rodrigograca31** [comment]
Can we close this issued then?
