### ISSUE TITLE
It gave me empty output [{}]

### ISSUE THREAD

**Issue by almgwary** [DataGarage/node-xls-json#35]
I used some files and your test file also, it keep showing me empty output [{}],
I am running on:
Windows: 7
NodeJS: v8.11.2

**Comment by rodrigograca31** [comment]
hummmm, :thinking: 

I've just run the example and works.
Try to remove the sheet name field.

```
NodeJS: v8.10.0
Linux Mint
```

**Comment by rodrigograca31** [comment]
That seems to be the problem.
